# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20160706_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d/thumbnails'),
        ),
    ]
