# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 15:17
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_remove_photo_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='%Y/%m/%d'),
        ),
    ]
