# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_auto_20160707_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='thumb/%Y/%m/%d'),
        ),
    ]
