# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_photo_thumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AlterField(
            model_name='photo',
            name='thumb',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='%Y/%m/%d/thumb'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
